services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - internal-network
  
networks:
  internal-network:
    driver: bridge